language: node_js
node_js:
  - "4"
sudo: false
script: npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "maclev.io"
  region: us-east-1
  skip_cleanup: true
  local_dir: www
  on:
    branch: master
  acl: public_read
