language: node_js
node_js:
  - "4"
sudo: false
script: npm run build
deploy:
  provider: s3
  access_key_id:
    secure: "15m3++7vttzQr3iAHum1CdyamNdtmnwHQgiEi/lrTzUThGQgQ0CUc3n5yJhMAPqHeYFejMERdXlGhF6FpoOLyVgDZrecV7m94DED7W8TSAzAPVDLjGwqr5DpVLIG8A0ACfl6WyytXUd9r5HtvMJPEWXArlCoE2n+Z3A2v+YdKhLSjSSdm8zgL266rAHDW29a44HEo8mGrR0mtx5tCX2I/95X2jdqWCpF7XmWrVQCh6oob+bch5qK/GLdyVcCpv4wcq+PYBbKOFDP4ipBoIPc8LsP+dUsvyxlw6+byJtj42P2mqz2U75RAmVdZxcHNlF/iRgrfKzEOpoLr4guAh3bpBmTljC4cfxiH2jvwbxHSGSVmcgR2Yru1YI39PXMLZ5ent9ZHjeda+Ql+lPoN2QIDLpi9h9wgvtIE/oXY6VmCmu/+vxpKfdmq9awmGzfqhWrCrVxX8bBNs7SXht3dA0xW0WCXRNXQyjIFCoTFhih4norAkH4FKWEcosDBC26KA5GASktRKiujN0t9VEdNCCIpGsTVIvx4cMzY4iD9IcckwDHS5saSA2ygp415DyezyPMn2QEPE/QcRzfffKwlKuA/a9MAyvpAQPxV2d0EGBBPRiYee0GhNK2yAGRMXJVlup2NWSpW+I3ddFznNyTFaoPUFOF7bfAxk3Z4GKk/fqoFTw="
  secret_access_key:
    secure: "NU/+LLBTCeZp4zmgBzIFkmqXtTn8OSkryBBkKovvP0zdFPdNiE5lXYdI5XStdAizDhJAPHgmt5wXrq6hdqALLma0V6bRBsoS6NvLVfy+rB2oiSkUfp7cR0CU/kDQAzjWUgN9agUUweMfcIjUQofxpzzOCcdWd1lESCfAywzeKOh95KcnR0Yzpdshtgy1S4QGM6INN83UcvEAc+79ppGtU5s3E2GKad0i837wHiCZKsu4sCyVPQYonMC1Q+lGm7unm5RcGtKxUZV3oqVhxORdjaz6GOTcFSg8jnTMaOVo+aFp/iS7n5HTfrUbB5BiShC4c4u3nrks8S0JYRV8mIXbfKWid0s8yyqrhaDPsEOIjVXviDCrJaqQgaWboW2U2xIlz92h8RVoLebjX9fb0ZpG9+ZjOdwYYml2cuqeyt4G25lM3YKYqhpufQg0fhP8uzp7tZntH5PuoV0CqeoTYA/uaNcb7SjeBEvL59mjFTeRnisQ8uyrYFFYDCO/G56N4CjoyhymFLV+5Sag1dpA4+jQyIdmATlsfdQOcVywQMAOY0ak9U1fpsci3WGCn/tZb+4QWIIGgbq41oegzaavxrZtLY1VGhl8iqx245w2ruRe/PfLpPQ6FJZkCXaZyrCU5c+CuxBYDlHm+Oa4xVWMcs9rxZbNGvD01CnCEwrUfS71w0o="
  bucket: "maclev.io"
  region: us-east-1
  skip_cleanup: true
  local_dir: www
